// Navigation
export const BOTTOM_NAVIGATION_BAR_HEIGHT = 90;
export const BOTTOM_NAVIGATION_ICON_SIZE = 28;
export const BOTTOM_NAVIGATION_BUTTON_SIZE = 50;
export const OSTRACON_BUTTON_SPACE = 120;
export const OSTRACON_ICON_SIZE = 34;
export const OSTRACON_BUTTON_SIZE = 85;
